"""Per-country playlist indexes, across the sources Winnotix knows about.

Neither upstream project publishes anything machine-readable listing its
per-country playlists, so Winnotix ships an index for each, generated by
tools/generate_catalogue.py and tools/generate_iptv_org_catalogue.py.

  Free-TV   ~95 playlists, ~2,000 channels. The UK's is 55.
  iptv-org  185 playlists, ~11,000 channels. The UK's is 310, the US's 1,465.

A country usually appears in both, which is the point: they overlap little and
one is often live where the other is dead. Entries carry their source so the
picker can be filtered and so two entries for the same country cannot collide
as providers -- "Free-TV UK" and "iptv-org United Kingdom".

These are convenience indexes only. Adding an entry creates an ordinary provider
pointing at the recorded URL, so the playlist itself is always fetched fresh and
a stale channel count here is cosmetic.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from .paths import resources_dir

FREE_TV = "Free-TV"
IPTV_ORG = "iptv-org"

# Source label -> the resource file holding its index. Order is the order the
# picker lists them in.
CATALOGUE_FILES = {
    FREE_TV: "free_tv_catalogue.json",
    IPTV_ORG: "iptv_org_catalogue.json",
}

# Kept for callers that only want the original index.
CATALOGUE_FILE = CATALOGUE_FILES[FREE_TV]


@dataclass(frozen=True)
class CatalogueEntry:
    name: str
    code: str
    url: str
    channels: int
    source: str = FREE_TV
    combined: bool = False
    """A source's whole-world playlist rather than one country's."""

    @property
    def provider_name(self) -> str:
        """Distinguish these from a hand-added provider, and from each other."""
        return f"{self.source} {self.name}"


@lru_cache(maxsize=1)
def load() -> list[CatalogueEntry]:
    """Every source's entries, in CATALOGUE_FILES order."""
    entries: list[CatalogueEntry] = []
    for source, filename in CATALOGUE_FILES.items():
        entries.extend(load_file(resources_dir() / filename, source))
    return entries


def sources() -> list[str]:
    """Source labels that actually have entries bundled."""
    present = {e.source for e in load()}
    return [s for s in CATALOGUE_FILES if s in present]


def load_file(path: Path, source: str = FREE_TV) -> list[CatalogueEntry]:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except FileNotFoundError:
        return []
    except (json.JSONDecodeError, OSError) as exc:
        print(f"[winnotix] could not read the playlist catalogue {path}: {exc}")
        return []

    entries = []
    for raw in data.get("playlists", []):
        if not raw.get("name") or not raw.get("url"):
            continue
        entries.append(CatalogueEntry(
            name=raw["name"],
            code=(raw.get("code") or "").upper(),
            url=raw["url"],
            channels=int(raw.get("channels") or 0),
            source=source,
            combined=bool(raw.get("combined")),
        ))
    return entries


def search(term: str, entries: list[CatalogueEntry] | None = None,
           source: str | None = None) -> list[CatalogueEntry]:
    """Match on name, ISO code, or a country name that resolves to one.

    Free-TV takes its names from the playlists themselves, which call the United
    Kingdom "UK" and the United States "USA", while iptv-org spells them out.
    Resolving the search term through the country tables means "uk", "united
    kingdom" and "britain" all find both sources' entries.

    `source` restricts to one source label; None means every source.
    """
    entries = entries if entries is not None else load()
    if source:
        entries = [e for e in entries if e.source == source]

    needle = term.strip().lower()
    if not needle:
        return list(entries)

    from .countries import code_for_name
    resolved = (code_for_name(needle) or "").lower()

    return [
        e for e in entries
        if needle in e.name.lower()
        or needle == e.code.lower()
        or (resolved and resolved == e.code.lower())
    ]


def order(entries: list[CatalogueEntry]) -> list[CatalogueEntry]:
    """Combined playlists first, then by name -- the picker's display order."""
    return sorted(entries, key=lambda e: (not e.combined, e.source, e.name.lower()))
