"""The Free-TV per-country playlist index.

The combined playlist Hypnotix defaults to is ~2,059 channels. The same repo
also publishes ~95 per-country playlists -- the UK's is 55 channels, Albania's
is 17 -- but nothing that lists them, so Winnotix ships an index generated by
tools/generate_catalogue.py.

This is a convenience index only. Adding an entry creates an ordinary provider
pointing at the recorded URL, so the playlist itself is always fetched fresh and
a stale channel count here is cosmetic.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from .paths import resources_dir

CATALOGUE_FILE = "free_tv_catalogue.json"


@dataclass(frozen=True)
class CatalogueEntry:
    name: str
    code: str
    url: str
    channels: int

    @property
    def provider_name(self) -> str:
        """Distinguish these from a hand-added provider of the same name."""
        return f"Free-TV {self.name}"


@lru_cache(maxsize=1)
def load(path: Path | None = None) -> list[CatalogueEntry]:
    path = path if path is not None else resources_dir() / CATALOGUE_FILE
    try:
        with open(path, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except FileNotFoundError:
        return []
    except (json.JSONDecodeError, OSError) as exc:
        print(f"[winnotix] could not read the playlist catalogue {path}: {exc}")
        return []

    entries = []
    for raw in data.get("playlists", []):
        if not raw.get("name") or not raw.get("url"):
            continue
        entries.append(CatalogueEntry(
            name=raw["name"],
            code=(raw.get("code") or "").upper(),
            url=raw["url"],
            channels=int(raw.get("channels") or 0),
        ))
    return entries


def search(term: str, entries: list[CatalogueEntry] | None = None
           ) -> list[CatalogueEntry]:
    """Match on name, ISO code, or a country name that resolves to one.

    The catalogue takes its names from the playlists themselves, which call the
    United Kingdom "UK" and the United States "USA". Resolving the search term
    through the country tables means "united kingdom" and "britain" find it too.
    """
    entries = entries if entries is not None else load()
    needle = term.strip().lower()
    if not needle:
        return list(entries)

    from .countries import code_for_name
    resolved = (code_for_name(needle) or "").lower()

    return [
        e for e in entries
        if needle in e.name.lower()
        or needle == e.code.lower()
        or (resolved and resolved == e.code.lower())
    ]
