#!/usr/bin/env python3
"""Regenerate resources/iptv_org_catalogue.json.

[iptv-org/iptv](https://github.com/iptv-org/iptv) is a much larger collection
than Free-TV -- ~1,465 channels for the US alone. Its repository stores channels
in `streams/`, split by where each stream comes from: `uk.m3u`, plus
`uk_pluto.m3u`, `uk_samsung.m3u`, `uk_rakuten.m3u` and so on. **Those raw files
are not what we point at.** They carry no `group-title` and no `tvg-logo`, so
they load as one flat, logo-less list.

Their CI publishes a processed playlist per country that merges every source
file for that country and adds both:

    https://iptv-org.github.io/iptv/countries/<code>.m3u

For the UK that is 310 channels across 43 categories with 308 logos, against
183 ungrouped and logo-less in `streams/uk.m3u`. So the merge the per-source
files need is one iptv-org already does, and better than we could locally.

    python tools/generate_iptv_org_catalogue.py                 # all countries
    python tools/generate_iptv_org_catalogue.py --repo newIPTVrepo

`--repo` only narrows which country codes are probed, using the local checkout's
`streams/` filenames; the counts still come from the published playlists,
because those are generated by CI and are not in the repository. As with the
Free-TV catalogue, this index is a convenience: Winnotix always fetches the
playlist itself at the recorded URL, so a stale count here is cosmetic.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "resources" / "iptv_org_catalogue.json"

SITE = "https://iptv-org.github.io/iptv/"
COUNTRIES_API = "https://iptv-org.github.io/api/countries.json"
# Grouped by country, so it lands on the categories page as country tiles
# with flags -- exactly like Free-TV's combined playlist. index.m3u would
# group by nothing useful, and index.category.m3u duplicates what a
# per-country playlist already gives you.
COMBINED = SITE + "index.country.m3u"

sys.path.insert(0, str(ROOT))
from winnotix.core.countries import code_for_name, flag_file  # noqa: E402


def get(url: str, timeout: int = 60, attempts: int = 3) -> str | None:
    """GET with retries -- a few hundred requests to one host will drop some."""
    request = urllib.request.Request(url, headers={"User-Agent": "winnotix"})
    for attempt in range(attempts):
        try:
            with urllib.request.urlopen(request, timeout=timeout) as response:
                return response.read().decode("utf-8", errors="ignore")
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                return None        # a country with no published playlist
            if attempt == attempts - 1:
                raise
        except (urllib.error.URLError, ConnectionError, TimeoutError):
            if attempt == attempts - 1:
                raise
        time.sleep(1 + attempt * 2)
    return None


def canonical_code(name: str, code: str) -> str:
    """Prefer the code our own country tables use.

    iptv-org codes the United Kingdom "UK"; ISO 3166-1 and our flag set say
    "GB". Normalising here means a search for "britain" finds this entry and
    the Free-TV one together, and the flag lookup succeeds.
    """
    resolved = code_for_name(name)
    if resolved and flag_file(resolved):
        return resolved
    return (code or "").upper()


def codes_from_repo(repo: Path) -> set[str]:
    """Country codes present in a checkout's streams/ folder.

    Filenames are `<code>.m3u` or `<code>_<source>.m3u`, so the code is
    everything before the first underscore.
    """
    folder = repo / "streams"
    if not folder.is_dir():
        raise SystemExit(f"no streams/ directory in {repo}")
    return {path.stem.split("_", 1)[0].upper() for path in folder.glob("*.m3u")}


def entry_for(country: dict) -> dict | None:
    code = (country.get("code") or "").lower()
    name = country.get("name") or code.upper()
    if not code:
        return None
    text = get(f"{SITE}countries/{code}.m3u", timeout=90)
    if not text:
        return None
    channels = text.count("#EXTINF")
    if not channels:
        return None
    return {
        "name": name,
        "code": canonical_code(name, country.get("code", "")),
        "file": f"{code}.m3u",
        "url": f"{SITE}countries/{code}.m3u",
        "channels": channels,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=None,
                        help="an iptv-org/iptv checkout; narrows which countries "
                             "are probed using its streams/ filenames")
    parser.add_argument("--jobs", type=int, default=8,
                        help="parallel requests (default: 8)")
    args = parser.parse_args()

    countries = json.loads(get(COUNTRIES_API))
    if args.repo is not None:
        wanted = codes_from_repo(args.repo)
        countries = [c for c in countries if (c.get("code") or "").upper() in wanted]
    print(f"probing {len(countries)} countries…", file=sys.stderr)

    with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        results = list(pool.map(entry_for, countries))
    entries = [e for e in results if e]
    entries.sort(key=lambda e: e["name"].lower())

    combined = get(COMBINED, timeout=180) or ""
    if combined:
        entries.insert(0, {
            "name": "All countries",
            "code": "",
            "file": "index.country.m3u",
            "url": COMBINED,
            "channels": combined.count("#EXTINF"),
            "combined": True,
        })

    payload = {
        "source": "https://github.com/iptv-org/iptv",
        "combined_url": COMBINED,
        "note": "Per-country playlists, published by iptv-org's CI. Each merges "
                "every source file for that country and carries logos and "
                "category group titles, which the repository's own streams/*.m3u "
                "files do not. Channel counts are indicative; the playlist itself "
                "is always fetched fresh at its url.",
        "playlists": entries,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                   encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}: {len(entries)} playlists, "
          f"{sum(e['channels'] for e in entries)} channels")
    flagless = [f"{e['name']} ({e['code']})" for e in entries
            if e["code"] and not flag_file(e["code"])]
    if flagless:
        print(f"  no bundled flag for: {', '.join(flagless)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
